var dir = require('node-dir');
var fs = require('fs');

var stream = fs.createWriteStream('index.d.ts');
var paths = [
    './engine/core/core.js',
    './engine/core/color.js',
    './engine/core/guid.js',
    './engine/core/time.js',
    // './engine/core/hash.js',
    './engine/core/uri.js',
    './engine/core/log.js',
    './engine/core/inheritance.js',
    './engine/core/path.js',
    './engine/core/string.js',
    './engine/core/debug.js',
    './engine/core/events.js',
    './engine/core/tags.js',
    // './engine/core/object-pool.js',
    './engine/core/platform.js',
    './engine/math/math.js',
    './engine/math/vec2.js',
    './engine/math/vec3.js',
    './engine/math/vec4.js',
    './engine/math/mat3.js',
    './engine/math/mat4.js',
    './engine/math/quat.js',
    './engine/math/curve.js',
    './engine/math/curve-set.js',
    './engine/shape/bounding-box.js',
    './engine/shape/bounding-sphere.js',
    './engine/shape/frustum.js',
    './engine/shape/plane.js',
    './engine/shape/ray.js',
    './engine/shape/oriented-box.js',
    './engine/graphics/graphics.js',
    // './engine/graphics/scope-id.js',
    // './engine/graphics/scope-space.js',
    // './engine/graphics/version.js',
    // './engine/graphics/versioned-object.js',
    './engine/graphics/vertex-iterator.js',
    './engine/graphics/vertex-format.js',
    './engine/graphics/vertex-buffer.js',
    './engine/graphics/index-buffer.js',
    './engine/graphics/transform-feedback.js',
    './engine/graphics/texture.js',
    './engine/graphics/render-target.js',
    // './engine/graphics/shader-input.js',
    './engine/graphics/shader.js',
    './engine/graphics/program-library.js',
    './engine/graphics/program-lib.js',
    './engine/graphics/device.js',
    './engine/graphics/chunks.js',
    // './engine/graphics/simple-post-effect.js',
    // './engine/graphics/prefilter-cubemap.js',
    // './engine/graphics/paraboloid.js',
    // './engine/graphics/program-lib/chunks/generated-shader-chunks.js',
    // './engine/graphics/program-lib/program-lib.js',
    // './engine/graphics/program-lib/basic.js',
    // './engine/graphics/program-lib/particle.js',
    // './engine/graphics/program-lib/standard.js',
    // './engine/graphics/program-lib/skybox.js',
    './engine/graphics/post-effect.js',
    './engine/scene/scene.js',
    './engine/scene/forward-renderer.js',
    './engine/scene/graph-node.js',
    './engine/scene/camera.js',
    // './engine/scene/light.js',
    './engine/scene/material.js',
    './engine/scene/basic-material.js',
    // './engine/scene/depth-material.js',
    './engine/scene/standard-material.js',
    './engine/scene/mesh.js',
    './engine/scene/skin.js',
    // './engine/scene/skin-partition.js',
    './engine/scene/morph.js',
    './engine/scene/model.js',
    // './engine/scene/particle-emitter.js',
    './engine/scene/pick.js',
    './engine/scene/procedural.js',
    // './engine/scene/default-material.js',
    './engine/scene/layer.js',
    './engine/scene/layer-composition.js',
    // './engine/scene/sprite.js',
    // './engine/scene/texture-atlas.js',
    // './engine/scene/stencil-parameters.js',
    './engine/anim/animation.js',
    './engine/anim/skeleton.js',
    './engine/sound/manager.js',
    './engine/sound/sound.js',
    './engine/sound/listener.js',
    './engine/sound/instance.js',
    './engine/sound/instance3d.js',
    './engine/audio/channel.js',
    './engine/audio/channel3d.js',
    './engine/input/input.js',
    './engine/input/mouse.js',
    './engine/input/keyboard.js',
    './engine/input/game-pads.js',
    './engine/input/touch.js',
    './engine/input/controller.js',
    './engine/input/element-input.js',
    './engine/vr/vr-manager.js',
    './engine/vr/vr-display.js',
    './engine/net/http.js',
    './engine/script/script-registry.js',
    './engine/script/script.js',
    './engine/framework/script.js',
    './engine/framework/application.js',
    // './engine/framework/stats.js',
    './engine/framework/components/registry.js',
    './engine/framework/components/system.js',
    './engine/framework/components/component.js',
    './engine/framework/components/data.js',
    './engine/framework/components/animation/component.js',
    './engine/framework/components/animation/system.js',
    './engine/framework/components/animation/data.js',
    './engine/framework/components/model/component.js',
    './engine/framework/components/model/system.js',
    // './engine/framework/components/model/data.js',
    './engine/framework/components/camera/component.js',
    './engine/framework/components/camera/system.js',
    // './engine/framework/components/camera/data.js',
    './engine/framework/components/camera/post-effect-queue.js',
    // './engine/framework/components/camera/post-effect-pass.js',
    './engine/framework/components/light/component.js',
    './engine/framework/components/light/system.js',
    // './engine/framework/components/light/data.js',
    './engine/framework/components/script/component.js',
    './engine/framework/components/script/system.js',
    // './engine/framework/components/script/data.js',
    // './engine/framework/components/script-legacy/component.js',
    // './engine/framework/components/script-legacy/system.js',
    // './engine/framework/components/script-legacy/data.js',
    './engine/framework/components/sound/constants.js',
    './engine/framework/components/sound/slot.js',
    './engine/framework/components/sound/component.js',
    './engine/framework/components/sound/system.js',
    // './engine/framework/components/sound/data.js',
    './engine/framework/components/audio-source/component.js',
    './engine/framework/components/audio-source/system.js',
    // './engine/framework/components/audio-source/data.js',
    './engine/framework/components/audio-listener/component.js',
    './engine/framework/components/audio-listener/system.js',
    // './engine/framework/components/audio-listener/data.js',
    './engine/framework/components/rigid-body/constants.js',
    './engine/framework/components/rigid-body/component.js',
    './engine/framework/components/rigid-body/system.js',
    // './engine/framework/components/rigid-body/data.js',
    // './engine/framework/components/collision/trigger.js',
    './engine/framework/components/collision/component.js',
    './engine/framework/components/collision/system.js',
    // './engine/framework/components/collision/data.js',
    './engine/framework/components/particle-system/component.js',
    './engine/framework/components/particle-system/system.js',
    // './engine/framework/components/particle-system/data.js',
    // './engine/framework/components/sprite/sprite-animation-clip.js',
    // './engine/framework/components/sprite/component.js',
    // './engine/framework/components/sprite/system.js',
    // './engine/framework/components/sprite/data.js',
    './engine/framework/components/screen/component.js',
    './engine/framework/components/screen/system.js',
    // './engine/framework/components/screen/data.js',
    './engine/framework/components/element/component.js',
    './engine/framework/components/element/system.js',
    // './engine/framework/components/element/data.js',
    // './engine/framework/components/element/image-element.js',
    // './engine/framework/components/element/text-element.js',
    './engine/framework/components/text/font.js',
    './engine/framework/components/zone/component.js',
    './engine/framework/components/zone/system.js',
    // './engine/framework/components/zone/data.js',
    './engine/framework/entity.js',
    './engine/resources/loader.js',
    './engine/resources/animation.js',
    // './engine/resources/audio.js',
    './engine/resources/cubemap.js',
    // './engine/resources/json.js',
    './engine/resources/material.js',
    './engine/resources/model.js',
    './engine/resources/script.js',
    // './engine/resources/text.js',
    // './engine/resources/binary.js',
    './engine/resources/texture.js',
    // './engine/resources/html.js',
    // './engine/resources/css.js',
    // './engine/resources/shader.js',
    // './engine/resources/scene.js',
    // './engine/resources/hierarchy.js',
    // './engine/resources/scene-settings.js',
    // './engine/resources/folder.js',
    // './engine/resources/font.js',
    // './engine/resources/texture-atlas.js',
    // './engine/resources/sprite.js',
    // './engine/resources/parser/json-model.js',
    // './engine/resources/parser/scene.js',
    './engine/asset/asset.js',
    // './engine/asset/asset-variants.js',
    './engine/asset/asset-registry.js',
    // './engine/backwards-compatibility.js',
    // './engine/scene/immediate.js',
    './engine/scene/lightmapper.js',
    './engine/scene/batching.js'
];

paths.forEach(path => {
    stream.write(`/// <reference path="${path.replace('.js', '.d.ts')}" />\n`);
});
stream.end();
